name: yoloworks_invoice
description: "A YoloWorks Invoice App"

publish_to: none

version: 1.0.3+10

environment:
  #  dart sdk 3.5.0
  #  flutter sdk 3.24.1 -> 3.29.3
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # NETWORK
  http: ^1.4.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  awesome_dio_interceptor: ^1.3.0
  
  # SERVICES
  equatable: ^2.0.7

  #UI & DESIGN
  shimmer: ^3.0.0
  lottie: ^3.3.1
  dotted_line: ^3.2.3
  easy_refresh: ^3.4.0
  fluttertoast: ^8.2.12
  dotted_border: ^2.1.0
  draggable_fab: ^0.1.4
  flutter_linkify: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.2.0
  flutter_styled_toast: ^2.2.1
  flutter_native_splash: ^2.4.6
  persistent_bottom_nav_bar: ^6.2.1
  flutter_floating_bottom_bar: ^1.3.0

  #UTILS
  intl: ^0.20.2
  event_bus: ^2.0.1
  url_launcher: ^6.3.1
  easy_debounce: ^2.0.3
  flutter_svg: ^2.1.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  syncfusion_flutter_charts: ^29.1.41
  flutter_inappwebview: ^6.1.5


  # SHARE
  share_plus: ^11.0.0
  permission_handler: ^12.0.1


  # FILE HANDLING
  open_filex: ^4.7.0


  # LOGGING
  sentry_flutter: ^8.14.2
  sentry_logging: ^8.14.2
  logging: ^1.3.0
  mixpanel_flutter: ^2.4.1

  # STATE MANAGEMENT
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Firebase Services
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.3

  # Custom Plugin
  vgts_plugin:
    git:
      url: https://github.com/santhoshvgts/vgts_plugin
      ref: flutter-version-upgrade
#  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  flutter_launcher_icons: ^0.14.3


dependency_overrides:
  intl: ^0.20.2
  package_info_plus: ^8.3.0



flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/logos/
    - assets/images/
    - assets/lottie_json/
    - shorebird.yaml

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700


#app_launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/yolo_app_icon.png"
  min_sdk_android: 21

#NATIVE SPLASH
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/splash_yolo_app_icon.png
  android_12:
    image: assets/logos/splash_yolo_app_icon.png
    color: "#FFFFFF"

   